### ISSUE TITLE
在用了，谢谢老哥

### ISSUE THREAD

**Issue by irunmyway** [weimingjue/BaseAdapter#1]
在用了，谢谢老哥

**Comment by weimingjue** [comment]
已经改成基于dataBinding了，更稳定、更好用哦

**Comment by irunmyway** [comment]
appreciate，但是在这个列表之中有个东西也挺麻烦，就是焦点问题，倘若在tv设备，焦点的问题就很严重了，mobile设备都挺好

**Comment by weimingjue** [comment]
焦点问题是view 方面的东西了。
在xml里将那个抢焦点view加上
` android:focusable="false"`

在其他需要焦点的view（都不需要可以随便找一个Recycler、ListView之外的控件）
`
    android:focusable="true"//其他任意view先占用焦点即可
    android:focusableInTouchMode="true"//其他任意view先占用焦点即可`

**Comment by irunmyway** [comment]
老哥，最后的更新是不是少了base包了！

**Comment by weimingjue** [comment]
哪个base包？现在是4.1.0相比之前的2.几移动了包名和修改了方法

**Comment by irunmyway** [comment]
就是存放baseViewHolder的那个base包，好像没有上传，看不到那个包了

**Comment by weimingjue** [comment]
有的，你看看 com.wang.container.holder.BaseViewHolder，你需要把原来的import删掉一下

**Comment by irunmyway** [comment]
![image](https://user-images.githubusercontent.com/33797433/91253696-064ade00-e793-11ea-9ea7-9a17152b365a.png)
真的没有啊

**Comment by weimingjue** [comment]
在这里，导的是adapter里的：
 //自己的适用于超复杂列表样式，如：聊天、首页等
    api 'com.github.weimingjue:BaseContainerAdapter:3.0.3'
